== stderr ==
c_t4.f:
   foo:
Warning on line 42 of t4tail.F: attempted division by zero
== C ==
/* c_t4.f -- translated by f2c (version @VSN).
   You must link the resulting object file with libf2c:
	on Microsoft Windows system, link with libf2c.lib;
	on Linux or Unix systems, link with .../path/to/libf2c.a -lm
	or, if you install libf2c.a in a standard place, with -lf2c -lm
	-- in that order, at the end of the command line, as in
		cc *.o -lf2c -lm
	Source for libf2c is in /netlib/f2c/libf2c.zip, e.g.,

		http://www.netlib.org/f2c/libf2c.zip
*/

#include "f2c.h"

/*     foo */
/*<       subroutine foo >*/
/* Subroutine */ int foo_(void)
{
    static real a, b, c__, d__;
    static integer i1, i2;

/*     put a number */
/*     into a variable */
/*<       a = 1 >*/
    a = 1.f;
/*     about to include t4inc1.f */
/*<       include 't4inc1.f' >*/
/*<       b = 2 >*/
/*     set i1 */
    i1 = 11;
/*     i1 was set */
/*<       i1 = 11 >*/
/*     after first include? */
    b = 2.f;
/*<       include 't4inc2.f' >*/
/*<       c = 3 >*/
    i2 = 22;
/* end of second include */
/*<       i2 = 22                                     ! catch >*/
    c__ = 3.f;
/*<       d = 1 / 0 >*/
    d__ = (real) (1 / 0);
/*<       end >*/
    return 0;
} /* foo_ */

