== stderr ==
c_tcom.f:
   tcom:
== C ==
/* c_tcom.f -- translated by f2c (version @VSN).
   You must link the resulting object file with libf2c:
	on Microsoft Windows system, link with libf2c.lib;
	on Linux or Unix systems, link with .../path/to/libf2c.a -lm
	or, if you install libf2c.a in a standard place, with -lf2c -lm
	-- in that order, at the end of the command line, as in
		cc *.o -lf2c -lm
	Source for libf2c is in /netlib/f2c/libf2c.zip, e.g.,

		http://www.netlib.org/f2c/libf2c.zip
*/

#include "f2c.h"

/*<       subroutine tcom >*/
/* Subroutine */ int tcom_(void)
{
    static real a, b;

/*<       include 'tcom1.f' >*/
/*<       a = 1 >*/
/*     before included statement */
    b = 2.f;
/*     after included statement */
/*<       b = 2 >*/
/*     after include */
/*     but we don't yet know */
/*     that there is no continuation */
    a = 1.f;
/*<       end >*/
    return 0;
} /* tcom_ */

