== stderr ==
ci_t3.f:
   foo:
== C ==
/* ci_t3.f -- translated by f2c (version @VSN).
   You must link the resulting object file with libf2c:
	on Microsoft Windows system, link with libf2c.lib;
	on Linux or Unix systems, link with .../path/to/libf2c.a -lm
	or, if you install libf2c.a in a standard place, with -lf2c -lm
	-- in that order, at the end of the command line, as in
		cc *.o -lf2c -lm
	Source for libf2c is in /netlib/f2c/libf2c.zip, e.g.,

		http://www.netlib.org/f2c/libf2c.zip
*/

#include "f2c.h"

/*<       subroutine foo >*/
/* Subroutine */ int foo_(void)
{
    /* Builtin functions */
    /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);

    /* Local variables */
    static char buf[40];

/*<       character buf*40 >*/
/* pling comment */
/*<       continue                                    ! no-op >*/
/*<       buf = 'pre' >*/
    s_copy(buf, "pre", (ftnlen)40, (ftnlen)3);
/*<       include 't3inc.f' >*/
/*<      $                                            ! incl comment >*/
    s_copy(buf, "included", (ftnlen)40, (ftnlen)8);
/*     looking? */
/*<       buf = 'post' >*/
    s_copy(buf, "post", (ftnlen)40, (ftnlen)4);
/*     is there a continuation? */
/*     finally we know not */
/*<       buf = 'end' >*/
    s_copy(buf, "end", (ftnlen)40, (ftnlen)3);
/*<       end >*/
    return 0;
} /* foo_ */

